services:
  vote:
    image: killebrew4dev/vote:latest
    ports:
      - 5000:80

  redis:
    image: redis:alpine

  db:
    image: postgres:15-alpine

  result:
    image: killebrew4dev/result:latest
    ports:
      - 5001:80

  worker:
    image: killebrew4dev/worker:latest
