volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: killebrew4dev/vote:latest
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - instavote

  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - instavote

  result:
    image: killebrew4dev/result:latest
    ports:
      - 5001:80
    depends_on:
      - redis
    networks:
      - instavote

  worker:
    image: killebrew4dev/worker:latest
    depends_on:
      - redis
      - db
    networks:
      - instavote
